<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <ApplicationId>com.osumusicplayer.mobile</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="11.3.20" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../OsuMusicPlayer.Mobile.App/OsuMusicPlayer.Mobile.App.csproj" />
  </ItemGroup>
</Project>
